name: Check build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ "**.md" ]

jobs:
  check-console-win:
    runs-on: windows-latest
    
    steps:
    # setup  
    - name: checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: microsoft/setup-msbuild@v1.0.2

    - name: Get version
      uses: naminodarie/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: ./NorthlightFontMaker/NorthlightFontMaker.csproj

    - name: publish NorthlightFontMaker
      run: msbuild .\NorthlightFontMaker\NorthlightFontMaker.csproj -t:restore -t:Build -t:Publish /p:PublishDir="../publish/console/windows" /p:Configuration=Release /p:SelfContained=False /p:PublishReadyToRun=False /p:PublishTrimmed=False

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows_${{steps.get-version.outputs.assembly-version}}
        path: ./publish/console/windows

  check-gui-win:
    runs-on: windows-latest
    
    steps:
    # setup  
    - name: checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: microsoft/setup-msbuild@v1.0.2

    - name: Get version
      uses: naminodarie/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: ./NorthlightFontMakerGUI/NorthlightFontMakerGUI.csproj

    - name: publish NorthlightFontMaker
      run: msbuild .\NorthlightFontMakerGUI\NorthlightFontMakerGUI.csproj -t:restore -t:Build -t:Publish /p:PublishDir="../publish/gui/windows" /p:Configuration=Release /p:SelfContained=False /p:PublishReadyToRun=False /p:PublishTrimmed=False

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows_gui_${{steps.get-version.outputs.assembly-version}}
        path: ./publish/gui/windows
 
  check-console-linux:
    runs-on: ubuntu-latest
    
    steps:
    # setup  
    - name: checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore NorthlightFontMaker/NorthlightFontMaker.csproj
    - name: Build
      run: dotnet build  NorthlightFontMaker/NorthlightFontMaker.csproj --no-restore
    - name: Test
      run: dotnet test NorthlightFontMaker/NorthlightFontMaker.csproj --no-build --verbosity normal
    - name: Publish
      run: dotnet publish NorthlightFontMaker/NorthlightFontMaker.csproj -c Release -o "publish/console/linux/"
      
    - name: Get version
      uses: naminodarie/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: ./NorthlightFontMaker/NorthlightFontMaker.csproj

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux_${{steps.get-version.outputs.assembly-version}}
        path: /home/runner/work/NorthlightFontMaker/NorthlightFontMaker/publish/console/linux
